name: supervised

datasets:

    multi_sprite:
        transform:
            filepath: src/transform.py
            fct: identity
        objectdataset:
            filepath: src/datasets.py
            class: MultiObjectDataset
        dataloader:
            filepath: src/datasets.py
            class: MultiObjectDataLoader
  
        params:
            height: 64
            width: 64
            vis_every: 50
            batch_size: 256
            learning_rate: 0.0004
            warmup_steps: 1000
            decay_rate: 0.5
            decay_steps: 50000
            num_epochs: 100
            load_parameters: 0
            num_slots: 5
            num_blocks: 5
            channel_base: 64
            bg_sigma: 0.09
            fg_sigma: 0.11
            
        prediction:
            all_carac:
                dim_points: 19
                checkpoint_file: ./checkpoints/multi_sprites_supervised_all_carac.ckpt
                filepath: ./data/multi_dsprites_all_carac.npz
                get_ground_truth:
                    filepath: src/preprocess.py
                    fct: ggt_multi_sprite_all_carac
                    
            rela_base:
                dim_points: 19
                dim_rela: 4
                obj_class_checkpoint_file: ./checkpoints/saved/slot_multi_sprites_supervised_all_carac.ckpt
                load_obj_class_parameters: 1 
                checkpoint_file: ./checkpoints/multi_sprites_supervised_rela_base.ckpt
                filepath: ./data/multi_dsprites_rela_base.npz
                get_ground_truth:
                    filepath: src/preprocess.py
                    fct: gtt_multi_sprite_rela_base

            rela_contact:
                dim_points: 19
                dim_rela: 8
                obj_class_checkpoint_file: ./checkpoints/saved/multi_sprites_supervised_all_carac_hexa.ckpt
                load_obj_class_parameters: 0 
                checkpoint_file: ./checkpoints/multi_sprites_supervised_rela_contact.ckpt
                filepath: ./data/multi_dsprites_rela_contact_new.npz
                get_ground_truth:
                    filepath: src/preprocess.py
                    fct: gtt_multi_sprite_rela_contact
                
              
              
    clevr:
            transform:
                filepath: src/transform.py
                fct: compose_2
            objectdataset:
                filepath: src/datasets.py
                class: Clevr
            dataloader:
                filepath: src/datasets.py
                class: MultiObjectDataLoader
      
            params:
                height: 128
                width: 128
                vis_every: 50
                batch_size: 256
                learning_rate: 0.0004
                warmup_steps: 1000
                decay_rate: 0.5
                decay_steps: 50000
                num_epochs: 1000
                load_parameters: 0
                num_slots: 10
                num_blocks: 6
                channel_base: 64
                bg_sigma: 0.09
                fg_sigma: 0.11
                
            prediction:
                all_carac:
                    dim_points: 19
                    checkpoint_file: ./checkpoints/slot_clevr_supervised_all_carac.ckpt
                    filepath: ./data/CLEVR_v1.0/
                    get_ground_truth:
                        filepath: src/preprocess.py
                        fct: ggt_clevr_all_carac

    multi_sprite_equal:
        transform:
            filepath: src/transform.py
            fct: identity
        objectdataset:
            filepath: src/datasets.py
            class: MultiObjectDataset
        dataloader:
            filepath: src/datasets.py
            class: MultiObjectDataLoader
  
        params:
            height: 64
            width: 64
            vis_every: 50
            batch_size: 256
            learning_rate: 0.0004
            warmup_steps: 1000
            decay_rate: 0.5
            decay_steps: 50000
            num_epochs: 200
            load_parameters: 0
            num_slots: 4
            num_blocks: 5
            channel_base: 64
            bg_sigma: 0.09
            fg_sigma: 0.11
            
        prediction:
            all_carac:
                dim_points: 18
                checkpoint_file: ./checkpoints/slot_multi_sprites_supervised_equal_carac.ckpt
                filepath: ./data/multi_dsprites_equal_carac.npz
                get_ground_truth:
                    filepath: src/preprocess.py
                    fct: ggt_multi_sprite_equal_carac