name: unsupervised

datasets:
    sprite:
        data:
          filepath: ./data/
        
        transform:
            filepath: src/transform.py
            fct: to_tensor
        objectdataset:
            filepath: src/datasets.py
            class: Sprites
        dataloader:
            filepath: ./
            class: default
  
        params:
            height: 64
            width: 64
            vis_every: 50
            batch_size: 64
            num_epochs: 20
            load_parameters: 1
            num_slots: 4
            num_blocks: 5
            channel_base: 64
            bg_sigma: 0.09
            fg_sigma: 0.11
            checkpoint_file: ./checkpoints/sprites.ckpt
        

        
    clevr:
        data:
          filepath: ./data/CLEVR_v1.0/
        
        transform:
            filepath: src/transform.py
            fct: compose_1
        objectdataset:
            filepath: src/datasets.py
            class: Clevr
        dataloader:
            filepath: src/datasets.py
            class: MultiObjectDataLoader
  
        params:
            height: 128
            width: 128
            vis_every: 50
            batch_size: 64
            num_epochs: 20
            load_parameters: 1
            num_slots: 11
            num_blocks: 6
            channel_base: 64
            bg_sigma: 0.09
            fg_sigma: 0.11
            checkpoint_file: ./checkpoints/clevr64.ckpt
            
    multi_sprite:
        data:
          filepath: ./data/multi_dsprites_210407_144010.npz
        
        transform:
            filepath: src/transform.py
            fct: identity
        objectdataset:
            filepath: src/datasets.py
            class: MultiObjectDataset
        dataloader:
            filepath: src/datasets.py
            class: MultiObjectDataLoader
  
        params:
            height: 64
            width: 64
            vis_every: 50
            batch_size: 64
            num_epochs: 20
            load_parameters: 1
            num_slots: 4
            num_blocks: 5
            channel_base: 64
            bg_sigma: 0.09
            fg_sigma: 0.11
            checkpoint_file: ./checkpoints/multi_sprites.ckpt

